// src/components/Features.js
import React from 'react';
import '../App.css'; // Ensure App.css is imported for styling

// Define the data for your features, including a placeholder for the icon
const featureData = [
  {
    icon: '📸',
    title: 'Input Flexibility',
    description: 'Provide an object via webcam capture, image upload, or by typing its name.'
  },
  {
    icon: '🧠',
    title: 'AI Identification',
    description: 'Our client-side AI (TensorFlow.js) intelligently identifies objects from images.'
  },
  {
    icon: '💡',
    title: 'AI-Powered Ideas',
    description: 'Get actionable upcycling ideas generated by an AI assistant.'
  },
  {
    icon: '✍️',
    title: 'User Refinement',
    description: 'Correct AI misidentifications, demonstrating human-in-the-loop refinement.'
  },
  {
    icon: '➕',
    title: 'Idea Contribution',
    description: 'Contribute your own unique upcycling ideas, which contributes to this community.'
  },
  {
    icon: '😊',
    title: 'User-Friendly UI',
    description: 'Enjoy a clear, intuitive, and responsive design for a seamless experience.'
  }
];


function Features() {
  return (
    <section className="features-section">
      <div className="features-header text-center"> {/* Add a div for header text */}
        <h2>Key Features</h2> {/* Updated heading text */}
        <p>Some of the key features of Upcyclr.</p>
      </div>

      <div className="features-grid">
        {featureData.map((feature, index) => (
          <div className="feature-item" key={index}> {/* Use index as key for now */}
            <div className="feature-icon">{feature.icon}</div> {/* Icon placeholder */}
            <h3>{feature.title}</h3> {/* Feature title */}
            <p>{feature.description}</p> {/* Feature description */}
          </div>
        ))}
      </div>
    </section>
  );
}

export default Features;